### ISSUE TITLE
XLS an TimeRange in duration

### ISSUE THREAD

**Issue by sidlmschulte** [maximedrn/opensea-automatic-bulk-upload-and-sale#114]
Hi there, thank you very much for your code
it works for perfect for me with json files
but in Excel i will use duration and this will not work

i can see that the agent will not klick the right dates - in json this works

where is my problem ? - Thak you very much for your time 

best reguards -- Michael 

here is my csv:

file_path;; nft_name;; external_link;; description;; collection;; properties;; levels;; stats;; unlockable_content;; explicit_and_sensitive_content;; supply;; blockchain;; sale_type;; price;; method;; duration;; specific_buyer;; quantity
C:/Users/user/Pictures/Sportler/zu opensea/NTFsUploader/40.png;;PixelSports#0040;;;;One of our SportsPixel Collection : Artist: SchizoPixelCrypticsMiner#007;;SportsPixel Collection;;;;;;;;" [True, ""Thank you for purchasing my NFT!""]";; False;;1;; Ethereum;; Fixed Price;;0.1;;;;" [""18-02-2022 10:00"", ""17-08-2022 10:00""]";;;;1
C:/Users/user/Pictures/Sportler/zu opensea/NTFsUploader/41.png;;PixelSports#0041;;;;One of our SportsPixel Collection : Artist: SchizoPixelCrypticsMiner#007;;SportsPixel Collection;;;;;;;;" [True, ""Thank you for purchasing my NFT!""]";; False;;1;; Ethereum;; Fixed Price;;0.1;;;;" [""18-02-2022 10:00"", ""17-08-2022 10:00""]";;;;1

here is the screen for py:
Login to MetaMask. Logged to MetaMask.
Login to OpenSea. Logged to OpenSea.
Uploading NFT n°1/2. NFT uploaded.
Sale of the NFT n°1/2. NFT sale cancelled. Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x00DD69A3+2582947]
        Ordinal0 [0x00D6A6D1+2139857]
        Ordinal0 [0x00C63A98+1063576]
        Ordinal0 [0x00C8FF3E+1244990]
        Ordinal0 [0x00C9013B+1245499]
        Ordinal0 [0x00CB9F52+1417042]
        Ordinal0 [0x00CA8594+1344916]
        Ordinal0 [0x00CB834A+1409866]
        Ordinal0 [0x00CA8366+1344358]
        Ordinal0 [0x00C85176+1200502]
        Ordinal0 [0x00C86066+1204326]
        GetHandleVerifier [0x00F7BE02+1675858]
        GetHandleVerifier [0x0103036C+2414524]
        GetHandleVerifier [0x00E6BB01+560977]
        GetHandleVerifier [0x00E6A8D3+556323]
        Ordinal0 [0x00D7020E+2163214]
        Ordinal0 [0x00D75078+2183288]
        Ordinal0 [0x00D751C0+2183616]
        Ordinal0 [0x00D7EE1C+2223644]
        BaseThreadInitThunk [0x7709FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77E77A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77E77A6E+238]

Traceback (most recent call last):
  File "C:\opensea\opensea-automatic-bulk-upload-and-sale-master\main.py", line 803, in <module>
    web = Webdriver(browser)  # Start a webdriver.
  File "C:\opensea\opensea-automatic-bulk-upload-and-sale-master\main.py", line 214, in __init__
    self.driver = self.chrome() if browser == 0 else self.firefox()
  File "C:\opensea\opensea-automatic-bulk-upload-and-sale-master\main.py", line 227, in chrome
    driver = webdriver.Chrome(service=Service(  # DeprecationWarning using
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 268, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 359, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 422, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 421, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 443, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\request.py", line 78, in request
    return self.request_encode_body(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
^C
C:\opensea\opensea-automatic-bulk-upload-and-sale-master>

**Comment by maximedrn** [comment]
Try with this:
```
file_path;; nft_name;; external_link;; description;; collection;; properties;; levels;; stats;; unlockable_content;; explicit_and_sensitive_content;; supply;; blockchain;; sale_type;; price;; method;; duration;; specific_buyer;; quantity
C:/Users/user/Pictures/Sportler/zu opensea/NTFsUploader/40.png;; PixelSports#0040;; ;; One of our SportsPixel Collection : Artist: SchizoPixelCrypticsMiner#007;; SportsPixel Collection;; ;; ;; ;; [True, "Thank you for purchasing my NFT!"];; False;; 1;; Ethereum;; Fixed Price;; 0.1;; ;; ["18-02-2022 10:00", "17-08-2022 10:00"];; ;; 1
C:/Users/user/Pictures/Sportler/zu opensea/NTFsUploader/41.png;; PixelSports#0041;; ;; One of our SportsPixel Collection : Artist: SchizoPixelCrypticsMiner#007;; SportsPixel Collection;; ;; ;; ;; [True, "Thank you for purchasing my NFT!"];; False;; 1;; Ethereum;; Fixed Price;; 0.1;; ;; ["18-02-2022 10:00", "17-08-2022 10:00"] ;; ;; 1
```
You have this:
```
file_path;; nft_name;; external_link;; description;; collection;; properties;; levels;; stats;; unlockable_content;; explicit_and_sensitive_content;; supply;; blockchain;; sale_type;; price;; method;; duration;; specific_buyer;; quantity
C:/Users/user/Pictures/Sportler/zu opensea/NTFsUploader/40.png;;PixelSports#0040;;;;One of our SportsPixel Collection : Artist: SchizoPixelCrypticsMiner#007;;SportsPixel Collection;;;;;;;;" [True, ""Thank you for purchasing my NFT!""]";; False;;1;; Ethereum;; Fixed Price;;0.1;;;;" [""18-02-2022 10:00"", ""17-08-2022 10:00""]";;;;1
C:/Users/user/Pictures/Sportler/zu opensea/NTFsUploader/41.png;;PixelSports#0041;;;;One of our SportsPixel Collection : Artist: SchizoPixelCrypticsMiner#007;;SportsPixel Collection;;;;;;;;" [True, ""Thank you for purchasing my NFT!""]";; False;;1;; Ethereum;; Fixed Price;;0.1;;;;" [""18-02-2022 10:00"", ""17-08-2022 10:00""]";;;;1
```
I think the problem come from the duplicate " for duration and unlockable content.

**Comment by maximedrn** [comment]
I fixed a problem with the collection. This may also solve your problem :)
