### ISSUE TITLE
Unable to sign the metamask when putting only on sale.

### ISSUE THREAD

**Issue by abdurrehmanRasheed12** [maximedrn/opensea-automatic-bulk-upload-and-sale#201]
Everything is working fine except for the last signature into metamask to put nft on sale.
```
{
  "nft": [
    {
      "nft_url": "https://opensea.io/assets/0x495f947276749ce646f68ac8c248420045cb7b5e/20033650643036269370804484394902981560079947123591047934100145726185113911297",
      "supply": 1,
      "blockchain": "Ethereum",
      "sale_type": "Fixed Price",
      "price": 0.014,
      "method": [],
      "duration": ["01-04-2022 00:00", "30-08-2022 23:59"],
      "specific_buyer": [false],
      "quantity": 1
    }
  ]
}
I have created just one JSON file to check weather sale only is working or not.
![fiverrrr](https://user-images.githubusercontent.com/62388253/159900424-a089fb38-7102-451f-afe0-9be6edca35bc.png)

**Comment by maximedrn** [comment]
It seems that my fix on the new Wyvern 2.3 contracts is not working. I will take a look and fix it :)

**Comment by abdurrehmanRasheed12** [comment]
While using Firefox it works perfect.

**Comment by Kisnobeats** [comment]
I think the same error for me, but using Google Chromedriver. I'm going to try Firefox now.

"Sale of the NFT. NFT sale cancelled. Message: Cannot sign the MetaMask contract."

**Comment by abdurrehmanRasheed12** [comment]
Try using firefox with high speed internet.

**Comment by Kisnobeats** [comment]
I downloaded the geckodriver,  placed it in the assets folder, and this is what happens...

"Traceback (most recent call last):
  File "C:\Users\16179\Desktop\opensea-automatic-bulk-upload-and-sale-master\main.py", line 949, in <module>
    web = Webdriver(browser, browser_path)  # Start a new webdriver.
  File "C:\Users\16179\Desktop\opensea-automatic-bulk-upload-and-sale-master\main.py", line 244, in __init__
    self.driver = self.chrome() if browser == 0 else self.firefox()
  File "C:\Users\16179\Desktop\opensea-automatic-bulk-upload-and-sale-master\main.py", line 274, in firefox
    driver = webdriver.Firefox(service=SG(  # DeprecationWarning using
  File "C:\Users\16179\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 181, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\16179\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 269, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\16179\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\16179\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\16179\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line"

**Comment by abdurrehmanRasheed12** [comment]
Do not download the drivers separately. Install all the requirements given and choose the drivers option when asked.

**Comment by maximedrn** [comment]
> While using Firefox it works perfect.

It's because it uses a different version of the extension for the two web browsers.
So it's a little bit different when it signs the contract.

**Comment by maximedrn** [comment]
> > While using Firefox it works perfect.
> 
> It's because it uses a different version of the extension for the two web browsers. So it's a little bit different when it signs the contract.

It's fixed for Google Chrome, there was no need to click on a button but you had to scroll down :/

**Comment by abdurrehmanRasheed12** [comment]
Thanks man !!
You are a life saver.
I'll buy your collection soon!!!!
