### ISSUE TITLE
About geckodriver

### ISSUE THREAD

**Issue by Joseph-Z** [maximedrn/opensea-automatic-bulk-upload-and-sale#206]
Why did I put geckoDriver in assets and it still shows that I did not put it in assets?

**Comment by Kisnobeats** [comment]
> Why did I put geckoDriver in assets and it still shows that I did not put it in assets?

I am getting the same problem.

"Traceback (most recent call last):
  File "C:\Users\16179\Desktop\opensea-automatic-bulk-upload-and-sale-master\main.py", line 949, in <module>
    web = Webdriver(browser, browser_path)  # Start a new webdriver.
  File "C:\Users\16179\Desktop\opensea-automatic-bulk-upload-and-sale-master\main.py", line 244, in __init__
    self.driver = self.chrome() if browser == 0 else self.firefox()
  File "C:\Users\16179\Desktop\opensea-automatic-bulk-upload-and-sale-master\main.py", line 274, in firefox
    driver = webdriver.Firefox(service=SG(  # DeprecationWarning using
  File "C:\Users\16179\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 181, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\16179\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 269, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\16179\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\16179\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\16179\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line"

**Comment by maximedrn** [comment]
Are you in the case where you can't download the web browser automatically?

**Comment by maximedrn** [comment]
> selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line"

Download Mozilla Firefox to your computer. The binary file (of the Firefox executable) is not found by the bot.

**Comment by Joseph-Z** [comment]
This is my error code 

[31mDownload the webdriver and place it in the assets/ folder.[0m

During handling of the above exception, another exception occurred:


During handling of the above exception, another exception occurred:

  File "[L:\opensea-automatic-bulk-upload-and-sale-master\main.py]()", line 949, in <module>
    GDM(log_level=0).install()  # Download the webdriver.

During handling of the above exception, another exception occurred:

  File "[L:\opensea-automatic-bulk-upload-and-sale-master\main.py]()", line 906, in exit_
    exit(f'{red}{message}{reset}')
  File "[L:\opensea-automatic-bulk-upload-and-sale-master\main.py]()", line 958, in <module>
    exit_('Download the webdriver and place it in the assets/ folder.')

**Comment by Joseph-Z** [comment]
My problem has been solved. It's my network problem here

**Comment by Kisnobeats** [comment]
> > selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line"
> 
> Download Mozilla Firefox to your computer. The binary file (of the Firefox executable) is not found by the bot.

Thank you for clarifying! I got it to work!

**Comment by Joseph-Z** [comment]
> Are you in the case where you can't download the web browser automatically?

yes,I can't download the web browser automatically.
