### ISSUE TITLE
Unable to login to OpenSea.

### ISSUE THREAD

**Issue by Vural78** [maximedrn/opensea-automatic-bulk-upload-and-sale#236]
Hi there

Although I tried periodically today, I could not log into Opensea with the file "main-manual-resolution.py".

Error shown:

```
Login to MetaMask. Logged to MetaMask.
Login to OpenSea. Login to OpenSea failed. Retrying.
Traceback (most recent call last):
  File "C:\Users\Vural\Desktop\opensea-automatic-bulk-upload-and-sale-master\main-manual-resolution.py", line 538, in login
    wallet.sign()  # Sign the login on OpenSea.
  File "C:\Users\Vural\Desktop\opensea-automatic-bulk-upload-and-sale-master\main-manual-resolution.py", line 366, in sign
    eval(f'self.{self.wallet_function}_sign()')
  File "<string>", line 1, in <module>
  File "C:\Users\Vural\Desktop\opensea-automatic-bulk-upload-and-sale-master\main-manual-resolution.py", line 421, in metamask_sign
    self.metamask_contract()  # Sign the contract.
  File "C:\Users\Vural\Desktop\opensea-automatic-bulk-upload-and-sale-master\main-manual-resolution.py", line 425, in metamask_contract
    web.window_handles(2)  # Switch to the MetaMask pop up tab.
  File "C:\Users\Vural\Desktop\opensea-automatic-bulk-upload-and-sale-master\main-manual-resolution.py", line 340, in window_handles
    WDW(self.driver, 10).until(lambda _: len(
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vural\Desktop\opensea-automatic-bulk-upload-and-sale-master\main-manual-resolution.py", line 545, in login
    wallet.contract()  # Sign the contract.
  File "C:\Users\Vural\Desktop\opensea-automatic-bulk-upload-and-sale-master\main-manual-resolution.py", line 370, in contract
    eval(f'self.{self.wallet_function}_contract({new_contract})')
  File "<string>", line 1, in <module>
  File "C:\Users\Vural\Desktop\opensea-automatic-bulk-upload-and-sale-master\main-manual-resolution.py", line 425, in metamask_contract
    web.window_handles(2)  # Switch to the MetaMask pop up tab.
  File "C:\Users\Vural\Desktop\opensea-automatic-bulk-upload-and-sale-master\main-manual-resolution.py", line 340, in window_handles
    WDW(self.driver, 10).until(lambda _: len(
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vural\Desktop\opensea-automatic-bulk-upload-and-sale-master\main-manual-resolution.py", line 1021, in <module>
    if opensea.login() is False:  # Connect to OpenSea.
  File "C:\Users\Vural\Desktop\opensea-automatic-bulk-upload-and-sale-master\main-manual-resolution.py", line 555, in login
    web.driver.refresh()  # Reload the page (login failed?).
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1062, in refresh
    self.execute(Command.REFRESH)
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=100.0.4896.60)
Stacktrace:
Backtrace:
        Ordinal0 [0x007C7413+2389011]
        Ordinal0 [0x00759F61+1941345]
        Ordinal0 [0x0064C658+837208]
        Ordinal0 [0x00634480+738432]
        Ordinal0 [0x00696999+1141145]
        Ordinal0 [0x006A3AA2+1194658]
        Ordinal0 [0x00693F66+1130342]
        Ordinal0 [0x0066E546+976198]
        Ordinal0 [0x0066F456+980054]
        GetHandleVerifier [0x00979632+1727522]
        GetHandleVerifier [0x00A2BA4D+2457661]
        GetHandleVerifier [0x0085EB81+569713]
        GetHandleVerifier [0x0085DD76+566118]
        Ordinal0 [0x00760B2B+1968939]
        Ordinal0 [0x00765988+1989000]
        Ordinal0 [0x00765A75+1989237]
        Ordinal0 [0x0076ECB1+2026673]
        BaseThreadInitThunk [0x769DFA29+25]
        RtlGetAppContainerNamedObjectPath [0x777E7A7E+286]
        RtlGetAppContainerNamedObjectPath [0x777E7A4E+238]
```

**Comment by maximedrn** [comment]
Maybe caused by Cloudflare protection.
Can you send me a video if this still happens :)

**Comment by EmilianoBruni** [comment]
Same problem. It always happens.

**Comment by maximedrn** [comment]
> Same problem. SOLVED add
> 
> `options.add_argument(' --disable-dev-shm-usage')`
> 
> to `def chrome(self) -> webdriver:`

Did this solve the problem for everyone using the manual version?

**Comment by EmilianoBruni** [comment]
> Did this solve the problem for everyone using the manual version?

I saw that main-manual-resolution.py has been merged with main.py starting from v.1.6.5 so, if you are using main-manual-resolution.py, you are using an old file and so the answer is no, not automatically. 

But you can try to apply this patch manually to you script and tell me (for curiosity) if it works.

**Comment by Vural78** [comment]
> > Same problem. SOLVED add
> > `options.add_argument(' --disable-dev-shm-usage')`
> > to `def chrome(self) -> webdriver:`
> 
> Did this solve the problem for everyone using the manual version?

Yes. seems to have fixed the problem for me.
I did not encounter any problem.

**Comment by maximedrn** [comment]
> Yes. seems to have fixed the problem for me. I did not encounter any problem.

So is this line `options.add_argument(' --disable-dev-shm-usage')` useful or not?

**Comment by Vural78** [comment]
> > Yes. seems to have fixed the problem for me. I did not encounter any problem.
> 
> So is this line `options.add_argument(' --disable-dev-shm-usage')` useful or not?

Yes, it is useful.

**Comment by Vural78** [comment]
Unfortunately, now I got the same error again. it didn't solve the problem.

**Comment by maximedrn** [comment]
Sometimes the second MetaMask pop-up window does not appear. This causes the bot to crash.
I will try to fix this.
