### ISSUE TITLE
Collection_Scraper

### ISSUE THREAD

**Issue by CryptoPunkFrens** [maximedrn/opensea-automatic-bulk-upload-and-sale#362]
I have this error when I run scraper.py
Expecting value: line 1 column 1 (char 0)
internal/modules/cjs/loader.js:905

**Comment by CryptoPunkFrens** [comment]
I have all 6 files in opensea-collection-scraper: index, opensea, package, requirements, scraper and utils
and still giving me this error:
I have this error when I run scraper.py
Expecting value: line 1 column 1 (char 0)
internal/modules/cjs/loader.js:905

**Comment by maximedrn** [comment]
Did you download all the files from the lastest version?

**Comment by CryptoPunkFrens** [comment]
YES ZIP FILE

**Comment by maximedrn** [comment]
In your command prompt, type:
```
node index.js --collection your-collection-url
```
And tell me if it displays an error.

**Comment by CryptoPunkFrens** [comment]
did I do command right?
C:\Users\Design3>node index.js --collection https://opensea.io/collection/boardapeartclub
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'C:\Users\Design3\index.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:746:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}

**Comment by maximedrn** [comment]
You're not in the tool folder, move to it using `cd "path/to/folder"`

**Comment by CryptoPunkFrens** [comment]
is this correct
C:\Users\Design3\Desktop\Uploading to Opensea\Collection_Scraper\opensea-collection-scraper>node index.js --collection crypto-punks-abstract-art
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'minimist'
Require stack:
- C:\Users\Design3\Desktop\Uploading to Opensea\Collection_Scraper\opensea-collection-scraper\index.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:746:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:974:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:93:18)←[39m
    at Object.<anonymous> (C:\Users\Design3\Desktop\Uploading to Opensea\Collection_Scraper\opensea-collection-scraper\index.js:1:12)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1085:14)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:950:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:790:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'C:\\Users\\Design3\\Desktop\\Uploading to Opensea\\Collection_Scraper\\opensea-collection-scraper\\index.js'←[39m
  ]
}

**Comment by maximedrn** [comment]
Now, install the modules:
```
npm install
```

**Comment by CryptoPunkFrens** [comment]
ok thank you it's working now
so do I need to run npm install on every update???

**Comment by maximedrn** [comment]
This command create a `node_modules/` folder.
On every update, you can replace only the `.py` and `.js` files, so you do not have to retype the command.

However, in case you update your browser, it can create an error. So you must delete the `node_modules/` folder and the `package-lock.json` file.

**Comment by CryptoPunkFrens** [comment]
now I have this

What is your collection URL? https://opensea.io/collection/crypto-punks-abstract-art
Scraping collection https://opensea.io/collection/crypto-punks-abstract-art.
5956 diversified element(s) found.

Something went wrong.
'asset'

**Comment by maximedrn** [comment]
Downloas version 1.7.1, it fixes this API issue

**Comment by CryptoPunkFrens** [comment]
where to download

**Comment by maximedrn** [comment]
On Gumroad if you have an account or from the mail you received.

**Comment by CryptoPunkFrens** [comment]
I did update from  https://maximedrn.gumroad.com/l/opensea-collection-scraper

**Comment by CryptoPunkFrens** [comment]
ok I didn't know you send another update yesterday, I downloaded and it's working now, thanks a million

**Comment by CryptoPunkFrens** [comment]
what's wrong with this now
C:\Users\Design3\Desktop\Uploading to Opensea\Deletion>delete.py
Traceback (most recent call last):
  File "C:\Users\Design3\Desktop\Uploading to Opensea\Deletion\delete.py", line 26, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 17, in <module>
ImportError: attempted relative import with no known parent package

**Comment by maximedrn** [comment]
Move the `delete.py` file to the `app/services/processes/` folder, run the `main.py` file and select the "Delete" option.

**Comment by CryptoPunkFrens** [comment]
I have this error now
NFT n°1/8:
Uploading NFT. Upload failed. The file extension is not supported on OpenSea.
Uploading NFT. Upload failed. The file extension is not supported on OpenSea.
Metadata saved in the data/upload_and_sale_503a75cb.json file.

**Comment by maximedrn** [comment]
Select the "Delete NFTs" option

**Comment by CryptoPunkFrens** [comment]
can't be delite

**Comment by CryptoPunkFrens** [comment]
I have 8 missing nft

**Comment by CryptoPunkFrens** [comment]
I have this error even when I want to upload new collection now
NFT n°3/4598:
Uploading NFT. Upload failed. File doesn't exist or path is incorrect.
Uploading NFT. Upload failed. File doesn't exist or path is incorrect.
Metadata saved in the data/upload_and_sale_423fa3d8.json file.

**Comment by maximedrn** [comment]
You've to complete the missing.json generated file with the required information.

**Comment by CryptoPunkFrens** [comment]
No I try everything and is not working, can't do it

NFT n°1/8:
Deletion of the NFT. NFT cannot be deleted.

NFT n°2/8:
Deletion of the NFT. NFT cannot be deleted.

NFT n°3/8:
Deletion of the NFT. NFT cannot be deleted.

NFT n°4/8:
Deletion of the NFT. NFT cannot be deleted.

**Comment by CryptoPunkFrens** [comment]
Please help

**Comment by maximedrn** [comment]
Can you give me a link to one of the NFTs you try to delete?
Note that if they are still listed on ETH, it will be impossible to delist them through this tool (it requires a paid transaction)

**Comment by CryptoPunkFrens** [comment]
I don't want to delete I have only missing files only 8 of them I have to upload and I'm doing all this on Polygon

**Comment by CryptoPunkFrens** [comment]
so what is the steps to upload missing.json

**Comment by CryptoPunkFrens** [comment]
duplicate.json I did and wasn't problem to delete but with missing.json by choosing delete option I have this error
NFT n°4/8:
Deletion of the NFT. NFT cannot be deleted.
so maybe I need to choose another option????

**Comment by maximedrn** [comment]
Open the `missing_xxxx` `.json`, `.xlsx` or `.csv` file and edit it with the missing details.
Then run the `main.py` script and select "Upload & Sale".

**Comment by CryptoPunkFrens** [comment]
now I have this problem
C:\Users\bilja\.wdm\drivers\chromedriver\win32\103.0.5060.53\chromedriver.exe
Something went wrong.
Extra data: line 46 column 10 (char 1633)

**Comment by maximedrn** [comment]
Can you send me the selected file? There is an error on line 46

**Comment by CryptoPunkFrens** [comment]
[missing_a519c2f9.zip](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/9128284/missing_a519c2f9.zip)

**Comment by CryptoPunkFrens** [comment]
please let me know where is the mistake

**Comment by maximedrn** [comment]
[missing_a519c2f9-fixed.zip](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/9128429/missing_a519c2f9-fixed.zip)

**Comment by CryptoPunkFrens** [comment]
now I have error [500] on opensea next to baton create

**Comment by CryptoPunkFrens** [comment]
today is not my day

**Comment by CryptoPunkFrens** [comment]
NFT n°1/142:
Uploading NFT. Solving the reCAPTCHA. Solved. Upload failed.
Uploading NFT. Solving the reCAPTCHA. Solved. Upload failed.
Metadata saved in the data/upload_and_sale_88109957.json file.

NFT n°2/142:
Uploading NFT. Solving the reCAPTCHA. Solved. Upload failed.
Uploading NFT. Solving the reCAPTCHA. Solved. Upload failed.
Metadata saved in the data/upload_and_sale_88109957.json file.

**Comment by maximedrn** [comment]
and what's the error displayed after [500]?

**Comment by CryptoPunkFrens** [comment]
![500 error](https://user-images.githubusercontent.com/108060093/179473635-1d72b80f-6cf4-41ac-a0c3-3a574c725d88.png)

**Comment by CryptoPunkFrens** [comment]
I still have this error

**Comment by maximedrn** [comment]
Can you change your network and try again? If it still doesn't work, contact OpenSea.

**Comment by CryptoPunkFrens** [comment]
Hi Maxime!
I have some problem with deleting NFT's, I did run the scraper and created file but when I run deleting error is coming : NFT cannot be deleted. What I'm doing wrong? Please help
