### ISSUE TITLE
there is erros and doesnt let me open main.py

### ISSUE THREAD

**Issue by hackcript** [maximedrn/opensea-automatic-bulk-upload-and-sale#421]
there is erros and doesnt let me open main.py here are mthe errors Traceback (most recent call last):
  File "C:\Users\Santy\Desktop\opensea-automatic-bulk-upload-and-sale\main.py", line 17, in <module>
    from app.utils.colors import RED, YELLOW, RESET
  File "C:\Users\Santy\Desktop\opensea-automatic-bulk-upload-and-sale\app\utils\colors.py", line 17, in <module>
    from colorama import init, Fore, Style
ModuleNotFoundError: No module named 'colorama'

**Comment by maximedrn** [comment]
https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/wiki/Installation-and-configuration#installation-and-configuration-of-the-bot
