### ISSUE TITLE
TypeError in web driverfile.py

### ISSUE THREAD

**Issue by NirmalSankalana** [maximedrn/opensea-automatic-bulk-upload-and-sale#438]
Traceback (most recent call last):
  File "F:\opensea-automatic-bulk-upload-and-sale\main.py", line 32, in <module>
    from app.services.webdriver import download_browser, Webdriver
  File "F:\opensea-automatic-bulk-upload-and-sale\app\services\webdriver.py", line 46, in <module>
    class Webdriver:
  File "F:\opensea-automatic-bulk-upload-and-sale\app\services\webdriver.py", line 106, in Webdriver
    def chrome_version(default_version: bool = False) -> float | int:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by maximedrn** [comment]
Fixed: https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/commit/285b4cc0aedbfcc3e66a1026c15096659446ca31
