### ISSUE TITLE
Index List Error

### ISSUE THREAD

**Issue by AndroidTutorialsyt** [maximedrn/opensea-automatic-bulk-upload-and-sale#78]
Traceback (most recent call last):
  File "C:\Users\asus\OneDrive\Desktop\opensea-automatic-bulk-upload-and-sale-1ab3889acf8ab9cf749bec6aa5fa753ad259d018\opensea-automatic-bulk-upload-and-sale-1ab3889acf8ab9cf749bec6aa5fa753ad259d018\main.py", line 716, in <module>
    structure.get_data(nft_number)  # Structure the data of the NFT.
  File "C:\Users\asus\OneDrive\Desktop\opensea-automatic-bulk-upload-and-sale-1ab3889acf8ab9cf749bec6aa5fa753ad259d018\opensea-automatic-bulk-upload-and-sale-1ab3889acf8ab9cf749bec6aa5fa753ad259d018\main.py", line 103, in get_data
    eval('self.structure_' + self.extension + '()')
  File "<string>", line 1, in <module>
  File "C:\Users\asus\OneDrive\Desktop\opensea-automatic-bulk-upload-and-sale-1ab3889acf8ab9cf749bec6aa5fa753ad259d018\opensea-automatic-bulk-upload-and-sale-1ab3889acf8ab9cf749bec6aa5fa753ad259d018\main.py", line 111, in structure_json
    self.structure_data([self.dict_to_list(
  File "C:\Users\asus\OneDrive\Desktop\opensea-automatic-bulk-upload-and-sale-1ab3889acf8ab9cf749bec6aa5fa753ad259d018\opensea-automatic-bulk-upload-and-sale-1ab3889acf8ab9cf749bec6aa5fa753ad259d018\main.py", line 178, in structure_data
    self.duration: list or str = nft_data[15 - index]
IndexError: list index out of range

Help me to Solve

**Comment by AndroidTutorialsyt** [comment]
{
"nft": [
    {
      "nft_name": "Angry Shark #1",
      "description": "Angry Shark Collection",
      "file_path": "C:/Users/asus/OneDrive/Desktop/generate-nfts-main/generate-nfts-main/layers/build//1.png",
      "dna": "87e3364b1aed289ea61a06620d41d79310f73318",
      "edition": 1,
      "date": 1643558854594,
      "collection": "Angry Shark Collection",
      "unlockable_content": [
        true,
        "Content"
      ],
      "explicit_and_sensitive_content": true,
      "supply": 1,
      "blockchain": "Polygon",
      "price": 0.5,
      "quantity": "",
      "properties": [
        {
          "type": "Background",
          "value": "Yellow"
        },
        {
          "type": "Body",
          "value": "Blue"
        },
        {
          "type": "Head Accessory",
          "value": "Pink Hat"
        },
        {
          "type": "Neck Accessory",
          "value": "Blue Diamond Chain"
        },
        {
          "type": "Hand Accessory",
          "value": "Trident"
        }
      ],
      "compiler": "HashLips Art Engine"
    }]
}

**Comment by AndroidTutorialsyt** [comment]
Ya Thanks a lot It helped me
