### ISSUE TITLE
Error while starting the bot PLEASE HELP

### ISSUE THREAD

**Issue by Fyzii** [maximedrn/opensea-automatic-bulk-upload-and-sale#93]
Hey!
I have a problem launching the bot, after selecting my metadata file the bot launches but crashes and shows me this message:

Traceback (most recent call last):
  File "C:\Users\dyfy7\Downloads\opensea-automatic-bulk-upload-and-sale-master\opensea-automatic-bulk-upload-and-sale-master\main.py", line 711, in <module>
    web = Webdriver()  # Start a new webdriver and init its methods.
  File "C:\Users\dyfy7\Downloads\opensea-automatic-bulk-upload-and-sale-master\opensea-automatic-bulk-upload-and-sale-master\main.py", line 211, in __init__
    self.driver = self.webdriver()  # Start new webdriver.
  File "C:\Users\dyfy7\Downloads\opensea-automatic-bulk-upload-and-sale-master\opensea-automatic-bulk-upload-and-sale-master\main.py", line 222, in webdriver
    driver = webdriver.Chrome(service=Service(  # DeprecationWarning using
TypeError: WebDriver.__init__() got an unexpected keyword argument 'service'

Please help me ;(

**Comment by maximedrn** [comment]
Update selenium by following this: https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale#known-issues-and-important-things-to-know

**Comment by Fyzii** [comment]
Oh thx it work
